worker_processes 1;
error_log  logs/error.log;
pid        logs/nginx.pid;
events { worker_connections 64; }
http {
    include      mime.types;
    default_type application/octet-stream;
    sendfile on;
    server {
        listen 443 ssl;
        server_name 192.168.10.156;
        ssl_certificate     C:/Ferramentas_SOCEM/AD-Manager/ssl/server.crt;
        ssl_certificate_key C:/Ferramentas_SOCEM/AD-Manager/ssl/server.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        root  C:/Ferramentas_SOCEM/AD-Manager;
        index azure-user-manager.html;
        location / { try_files $uri $uri/ =404; }
    }
    server {
        listen 80;
        server_name 192.168.10.156;
        return 301 https://$host$request_uri;
    }
}